Updating Dnotitia, a pioneering AI company that merges AI with data t…
aolofsson/awesome-semiconductor-startups pull request #107
Opened 2024-09-01 13:00 UTC by hello-dnotitia

Updating Dnotitia

2024-09-02 11:01 UTC, aolofsson commented
Do you/they design their own silicon. Not clear.

2024-09-07 18:55 UTC, afaerber requested changes
Note that while the pull request has been renamed, the Git commit still misleadingly says "updated" although it's adding a new entry.

All that said, I second @aolofsson's concerns: "Database" on the website sounds like software?

2024-09-07 18:55 UTC, afaerber commented on README.md
> +|[Dnotitia](https://dnotitia.com) | AI | 2023 | KR |Vector DPUs |
Your entry's description is getting cut off at the first comma ...

2024-09-07 18:55 UTC, afaerber commented on startups.csv
> +Dnotitia,dnotitia.com,AI,KR,2023,Vector DPUs, LLM systems, and HW/SW solutions for generative AI and AGI.
... you need quotes or some other escape mechanism for commas in the Comma Separated Values format.

2024-09-07 18:55 UTC, afaerber commented on startups.csv
> +Dnotitia,dnotitia.com,AI,KR,2023,Vector DPUs, LLM systems, and HW/SW solutions for generative AI and AGI.
The website actually spells it as "D.notitia", whereas here you spell it consistently without the dot.

2024-09-19 14:27 UTC, aolofsson commented
closing due to lack of response

2024-09-19 14:27 UTC, closed without merging